### ISSUE TITLE
Bug: showing the dialog can crash the app

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [nickbutcher/AnimatorDurationTile#5]
I got this exception :

10-23 13:09:45.316 28525-28525/uk.co.nickbutcher.animatordurationtile E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: uk.co.nickbutcher.animatordurationtile, PID: 28525
                                                                                        android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@53b0d53 is not valid; is your activity running?
                                                                                            at android.view.ViewRootImpl.setView(ViewRootImpl.java:678)
                                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                            at android.app.Dialog.show(Dialog.java:316)
                                                                                            at android.service.quicksettings.TileService.showDialog(TileService.java:232)
                                                                                            at uk.co.nickbutcher.animatordurationtile.SelectAnimatorDuration$1.run(SelectAnimatorDuration.java:69)
                                                                                            at android.service.quicksettings.TileService$H.handleMessage(TileService.java:401)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

It's a bit rare, but it happens.

**Comment by AndroidDeveloperLB** [comment]
Actually now that I look at it, it seems like a crash on Android OS itself, right?

**Comment by sampalmer** [comment]
Someone has created an Android bug report for this here:
https://issuetracker.google.com/issues/37105965

**Comment by AndroidDeveloperLB** [comment]
So... Why does it occur? Any way to handle it correctly?

**Comment by sampalmer** [comment]
I don't know, sorry. It's only happened a few times for me during development, and only for one user in Production.

**Comment by AndroidDeveloperLB** [comment]
ok thanks
